#!/usr/bin/env python3
"""Create responsive WebP copies without modifying the original photographs.

Requires Pillow with WebP support: python3 -m pip install Pillow
Run from any directory: python3 scripts/optimize-images.py
"""
import io
import json
import re
from pathlib import Path

from PIL import Image, ImageCms, ImageOps

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "index.html"
OUTPUT = ROOT / "images" / "web"


def main():
    page = PAGE.read_text()
    sources = sorted(set(re.findall(r'["\'](images/(?!web/)[^"\']+\.(?:jpe?g|png))["\']', page, re.I)))
    OUTPUT.mkdir(exist_ok=True)
    manifest = {}
    total_original = total_web = 0
    for source in sources:
        path = ROOT / source
        with Image.open(path) as original:
            photo = ImageOps.exif_transpose(original)
            profile = original.info.get("icc_profile")
            # Convert embedded camera/editing profiles so website copies retain colors.
            if profile:
                photo = ImageCms.profileToProfile(
                    photo, ImageCms.ImageCmsProfile(io.BytesIO(profile)),
                    ImageCms.createProfile("sRGB"), outputMode="RGBA" if "A" in photo.getbands() else "RGB"
                )
            else:
                photo = photo.convert("RGBA" if "A" in photo.getbands() else "RGB")
            width, height = photo.size
            targets = (80, 160) if "logo" in path.stem else (480, 960, 1600)
            variants = []
            for target in sorted(set(min(w, width) for w in targets)):
                resized = photo.resize((target, round(height * target / width)), Image.Resampling.LANCZOS)
                # Include original extension to avoid collisions between JPG/PNG stems.
                filename = f"{path.name}-{target}.webp"
                destination = OUTPUT / filename
                resized.save(destination, "WEBP", quality=86, method=6)
                variants.append({"src": f"images/web/{filename}", "width": target})
                total_web += destination.stat().st_size
            manifest[source] = {"width": width, "height": height, "variants": variants}
            total_original += path.stat().st_size
        print(f"Optimized {source}", flush=True)

    (ROOT / "scripts" / "image-manifest.js").write_text(
        "// Generated by scripts/optimize-images.py. Do not edit by hand.\n"
        + "const optimizedImages = " + json.dumps(manifest, separators=(",", ":")) + ";\n"
    )

    def update_image(match):
        tag = match.group(0)
        source_match = re.search(r'data-original="([^"]+)"', tag) or re.search(r'src="([^"]+)"', tag)
        if not source_match or source_match[1] not in manifest:
            return tag
        source = source_match[1]
        entry = manifest[source]
        variants = entry["variants"]
        srcset = ", ".join(f'{v["src"]} {v["width"]}w' for v in variants)
        hero = 'hero-carousel-image' in tag
        first = 'austin-michael-1.JPG' in source
        sizes = ('40px' if 'logo' in source else
                 '(max-width: 720px) calc(100vw - 60px), (max-width: 960px) calc(100vw - 92px), 340px' if hero else
                 '260px' if 'deeply-curious' in source else
                 '(max-width: 720px) calc(100vw - 60px), (max-width: 960px) 44vw, 350px')
        for attr in ('src', 'srcset', 'sizes', 'width', 'height', 'loading', 'decoding', 'fetchpriority', 'data-src', 'data-srcset', 'data-original'):
            tag = re.sub(r'\s' + attr + r'="[^"]*"', '', tag)
        deferred = hero and not first
        prefix = 'data-' if deferred else ''
        attrs = (f' data-original="{source}" {prefix}src="{variants[min(1,len(variants)-1)]["src"]}"'
                 f' {prefix}srcset="{srcset}" sizes="{sizes}"'
                 f' width="{entry["width"]}" height="{entry["height"]}" decoding="async"')
        if first:
            attrs += ' loading="eager" fetchpriority="high"'
        elif not hero and 'logo' not in source:
            attrs += ' loading="lazy"'
        return tag[:-1] + attrs + '>'

    page = re.sub(r'<img\b[^>]*>', update_image, page)
    if 'src="scripts/image-manifest.js"' not in page:
        page = page.replace('  <script>', '  <script src="scripts/image-manifest.js"></script>\n  <script>', 1)
    PAGE.write_text(page)
    print(json.dumps({"original_bytes": total_original, "web_bytes_all_sizes": total_web, "image_count": len(sources)}))


if __name__ == "__main__":
    main()
